spring:
  application:
    name: server-order
  config:
    import: nacos:server-order.yml  // 动态加载更新 Nacos 的配置内容
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8000



